export default EmojiEnum = {

    "[微笑]":require('../../resource/phiz/1.png'),
    "[发呆]": require('../../resource/phiz/2.png'),
    "[大笑]":require('../../resource/phiz/3.png'),
    "[白眼]":require('../../resource/phiz/4.png'),
    "[流汗]": require('../../resource/phiz/5.png'),
    "[1]":require('../../resource/phiz/6.png'),
    "[闭嘴]":require('../../resource/phiz/7.png'),
    "[酷]": require('../../resource/phiz/8.png'),
    "[囧]":require('../../resource/phiz/9.png'),
    "[喜欢]":require('../../resource/phiz/10.png'),
    "[3]": require('../../resource/phiz/11.png'),
    "[害羞]":require('../../resource/phiz/12.png'),
    "[4]":require('../../resource/phiz/13.png'),
    "[流泪]": require('../../resource/phiz/14.png'),
    "[寒]":require('../../resource/phiz/15.png'),
    "[发怒]":require('../../resource/phiz/16.png'),
    "[5]": require('../../resource/phiz/17.png'),
    "[6]":require('../../resource/phiz/18.png'),
    "[爱心]":require('../../resource/phiz/19.png'),
    "[心碎]": require('../../resource/phiz/20.png'),
    "[花]":require('../../resource/phiz/21.png'),
    "[7]":require('../../resource/phiz/22.png'),
    "[拳头]": require('../../resource/phiz/23.png'),
    "[8]":require('../../resource/phiz/24.png'),
    "[OK]": require('../../resource/phiz/25.png'),
    "[9]":require('../../resource/phiz/28.png'),
    "[强]":require('../../resource/phiz/29.png'),
    "[弱]": require('../../resource/phiz/30.png'),
    "[握手]":require('../../resource/phiz/32.png'),
    "[10]":require('../../resource/phiz/33.png'),
    "[胜利]": require('../../resource/phiz/34.png'),
    "[礼物]":require('../../resource/phiz/35.png'),
    "[咖啡]":require('../../resource/phiz/36.png'),
    "[饭]":require('../../resource/phiz/37.png'),
    "[足球]":require('../../resource/phiz/38.png'),
    "[啤酒]":require('../../resource/phiz/39.png'),
    "[太阳]": require('../../resource/phiz/40.png'),
}
