
import LocalizedStrings from 'react-native-localization';

let Strings = new LocalizedStrings({
    "en-US": {
        mainTab:{
            Chat:'Chat',
            Contacts:"Contacts",
            Discovery:"Discovery",
            Me:"Me"
        }
    },
    "zh-Hans-CN":{
        Common:{
            Info:"提醒",
            Error:"错误",
            AppName:"云信",
            Cancel:"取消",
            Delete:"删除",
            Complete:"完成",
            Back:"返回",
            Success:"成功",
            Confirm:"确定"
        },
        mainTab:{
            Chat:'云信',
            Contacts:"通讯录",
            Discovery:"发现",
            Me:"我"
        },
        AddFriend: {
            AddFriend:'添加朋友',
            PlaceHolder:'奇信号/QQ号/手机号',
        },
        Validate:{
            Title:"验证申请",
            ValidateMessage:"申请消息已经发送,等待对方验证",
            ValidateErrorMessage:"发送好友申请失败",
            Send:"发送",
            NeedValidateMessage:'你需要发送验证申请，等对方通过',
            RightOfCircle:'朋友圈权限',
            ForbidWatchCircle:'不让他(她)看我的朋友圈'
        },
        Zoom:{
            Zoom:'圈子',
            Scan:'扫一扫'
        },
        SearchNewFriend:{
            warnning:"你不能添加自己到通讯录",
            errorMessage:"该用户不存在",
            placeHolder:"奇信号/手机号",
            search:"搜索"
        },
        Search:{
            message:"没有搜索到本地相应的用户(群)信息",
            placeHolder:"好友昵称/好友云信号/群昵称",
            search:"搜索",
            Title:"搜索"
        },
        ScanCode:{
            Title:"二维码/条码"
        },
        ScanUnKnowPage:{
            Title:"扫描结果"
        },
        RecentList:{
            confirm:"删除后，将清空该聊天的消息记录",
            waitLogin:"登录验证中...",
            networkError:"网络连接不可用",
            receiveMessageError:"接收消息失败",
            connecting:"连接中...",
            receiveMessage:"接收消息...",
            reConnect:'网络重新连接中...'
        },
        Profile:{
            avator:"头像",
            nick:"昵称",
            QRcode:"我的二维码",
            more:"更多",
            cloudId:"云信号",
            Title:"个人信息",
            address:"我的地址"
        },
        HeadImage:{
            modalTitle:"更改你的头像",
            takePhoto:"拍照",
            chooseFromLibrary:"从手机相册选择",
            Title:"头像",
            rightLabel:"设置",
            leftLabel:"个人信息"
        },
        Gender:{
            male:"男",
            female:"女",
            Title:"设置性别"
        },
        Nickname:{
            errorMessage:'昵称不能为空',
            Title:"设置名字",

        },
        QRCode:{
            Title:'二维码',
            location:"中国"
        },
        NewFriend:{
            successMessage:"接受好友申請成功",
            errorMessage:"接受好友申請失败",
            deleteApplyFriend:"删除好友申请",
            added:"已添加",
            outOfDate:"已过期",
            Title:"新的朋友",
            contact:"通讯录",
            addFriend:"添加朋友",
            accept:"接受"
        },
        Me:{
            male:"男",
            female:"女",
            avator:"头像",
            nick:"昵称",
            QRcode:"我的二维码",
            cloudId:"云信号",
            gender:"性别",
            setting:"设置",
            unsetting:"未设置"
        },
        Setting:{
            changePassword:"修改密码",
            host:"设置服务器地址",
            version:"版本",
            Title:"设置",
            logout:"退出登录"
        },
        ConfigSetting:{
            emptyErrorMessage:"服务器地址不能为空",
            errorMessage:"文件保存出错,请重新再试",
            hostErrorMessage:"服务器地址输入不正确请重新输入",
            Title:"修改配置文件",
            enterLabel:"输入配置地址"
        },
        ChangePassword:{
            phoneNumberErrorMessage:"手机号码错误",
            changeSuccess:"密码修改成功，请重新登录!",
            changeFailed:"修改密码失败",
            passwordDifference:"两次输入密码不匹配",
            Title:"修改密码",
            oldPasswordLabel:"输入旧的密码",
            newPasswordLabel:"输入新密码",
            confirmPassword:"再次输入新密码"
        },
        Login:{
            phoneNumberErrorMessage:"手机号码错误",
            accountErrorMessage:"账号格式不正确",
            memberDoesntExist:"会员不存在",
            accountFreezen:"账号被冻结,请您联系工作人员",
            accountOrPasswordError:"账号或者密码错误",
            networkError:"网络出现故障，请检查当前设备网络连接状态",
            requestError:"登录请求出错",
            Title:"使用手机号登录",
            country:"中国",
            location:"国家/地区",
            phonePlaceHolder:"请输入手机号码",
            passwordPlaceHolder:"请输入密码",
            getValidateCode:"获取验证码",
            signin:"登录",
            forgetPassword:"忘记密码",
            register:"注册账号"
        },
        Register:{
            phoneNumberErrorMessage:"电话号码不能为空!",
            phoneNumberErrorInfo:"请填写正确的手机号!",
            maxTimesError:"达到今日次数限制!",
            phoneNumberExist:"手机号已存在!",
            phoneNumberNotExist:"手机号不存在!",
            requestErrorMessage:"请求频繁，亲稍后再试!",
            registerSuccess:"注册成功!",
            validateError:"验证码无效!",
            EmptyError:"信息不能为空!",
            Title:"手机号注册",
            country:"中国+86",
            location:"国家/地区",
            changeLocation:"更换地区",
            phonePlaceHolder:"请输入手机号码",
            passwordPlaceHolder:"请输入密码",
            getValidateCode:"获取验证码",
            validatePlaceHolder:"请输入验证码",
            passwordInfo:"密码由8-12位组成, 其中最少包括一个字母和数字，不能使用符号",
            info:"点击上面的“注册”按钮,即表示你同意",
            protocolInfo:"《APP隐私政策》",
            nick:"昵称",
            nickPlaceHolder:"例如：王凯",
            register:"注册",
            protocolInfoTwo:"《APP软件许可及服务协议》",
            plus:"和"
        },
        ResetPassword:{
            passwordEmptyError:"新密码或者确认密码不能为空，请重新输入",
            resetError:"重置密码发生错误，请重新设置",
            passwordDifference:"两次输入密码不一致,请重新输入",
            passwordInfo:"密码必须超过8位",
            Title:"重置密码",
            newPasswordLabel:"输入新密码",
            confirmPassword:"再次输入新密码"
        },
        FindPassword:{
            messageSendSuccess:"发送短信成功",
            messageSendError:"发送短信失败，请重新点击发送",
            phoneNumberErrorMessage:"手机号码错误",
            validateError:"无效验证码",
            validateEmptyError:"验证码不能为空",
            Title:"找回密码",
            country:"中国",
            location:"国家/地区",
            phonePlaceHolder:"请输入手机号码",
            validatePlaceHolder:"请输入验证码",
            getValidateCode:"获取验证码"
        },
        InfomationSetting:{
            Title:"资料设置",
            leftLabel:"详细资料",
            unWatchCricle:"不看他朋友圈",
            forbidWatchCricle:"不让他看我朋友圈",
            addBlackList:"加入黑名单"
        },
        Contact:{
            newFriend:"新的朋友",
            groupChat:"群聊",
            publicAccount:"公众号",
            contactCount:"位联系人",
            wait:"即将推出...",
        },
        GroupList:{
            searchPlaceHolder:"搜索",
            leftLabel:"通讯录",
            Title:"群聊",
            groupCount:"个群聊",
        },
        ChatSetting:{
            clearMessageSuccess:'清空聊天记录成功',
            Title:"聊天设置",
            setTopChat:"置顶聊天",
            setChatBackgroundImage:"设置当前聊天背景",
            clearMessage:"清空聊天记录",
        },
        ChatSettingBackgroundImage:{
            chooseFromLibrary:"从手机相册选择",
            takePhoto:"拍一张",
            clear:"清除背景图片",
            Title:"聊天背景"
        },
        GroupSettingBackgroundImage:{
            chooseFromLibrary:"从手机相册选择",
            takePhoto:"拍一张",
            clear:"清除背景图片",
            Title:"聊天背景"
        },
        ChooseClient:{
            startGroupChat:"发起群聊",
            chooseClient:"选中联系人",
            startGroupChatName:"发起的群聊",
            addMemberFailed:"添加成员失败",
            createGroupFailed:"创建失败",
            search:"搜索",
            chooseOneGroup:"选择一个群"
        },
        SelectGroup:{
            Title:"选择群聊"
        }
    }
})

export default Strings;