/**
 * Created by apple on 2017/10/25.
 */



export default ChatCommandEnum = {
    MSG_BODY_APP_APPLYFRIEND:1,
    MSG_BODY_APP_ADDFRIEND:2,
    MSG_BODY_APP_ADDGROUPMEMBER:3,
    MSG_BODY_APP_DELETEGROUPMEMBER:4,
    MSG_BODY_APP_EXITGROUP:5,
    MSG_BODY_APP_CREATEGROUP:6

}