/**
 * Created by apple on 2017/8/25.
 */


export default ChatCommandEnum = {
    MSG_BODY_CHAT_C2C : 1,
    MSG_BODY_CHAT_C2G : 2,
    MSG_BODY_CHAT__C2R : 3,
    MSG_BODY_CHAT_C2B:4,
    MSG_BODY_CHAT_B2C:5,
    MSG_BODY_APP_APPLYFRIEND:6,
    MSG_BODY_APP_ADDFRIEND:7,
    MSG_BODY_APP_ADDGROUPMEMBER:8,
    MSG_BODY_APP_DELETEGROUPMEMBER:9
}