/**
 * Created by apple on 2017/10/25.
 */



export default AppCommandEnum = {
    MSG_BODY_APP_APPLYFRIEND:1,
    MSG_BODY_APP_ADDFRIEND:2,
    MSG_BODY_APP_ADDGROUPMEMBER:3,
    MSG_BODY_APP_DELETEGROUPMEMBER:4,
    MSG_BODY_APP_EXITGROUP:5,
    MSG_BODY_APP_CREATEGROUP:6,
    MSG_BODY_APP_DISSOLUTIONGROUP:7,
    MSG_BODY_APP_MODIFYGROUPINFO:8,
}